ARG REGISTRY_PREFIX=""
FROM ${REGISTRY_PREFIX}base-imgs/bullseye

USER root

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    libopenblas-dev \
    libopenmpi-dev \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV ALF_HDF5_DIR="/var/lib/ALF_HDF5"
RUN git clone --depth 1 https://github.com/ALF-QMC/ALF.git /tmp/ALF && \
    cd /tmp/ALF && /bin/sh ./configure.sh gnu nompi HDF5 && \
    rm -rf /tmp/ALF /tmp/tmp.*

USER user
