ARG REGISTRY_PREFIX=""
FROM ${REGISTRY_PREFIX}base-imgs/bookworm

USER root

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    libblas-dev \
    liblapack-dev \
    libmpich-dev \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV ALF_HDF5_DIR="/var/lib/ALF_HDF5"
RUN git clone --branch 627-ci-pginvhpc-runtime-crash-illegal-instruction-exit-code-132-when-executing-progalfout --depth 1 https://github.com/ALF-QMC/ALF.git /tmp/ALF && \
    cd /tmp/ALF && /bin/sh ./configure.sh gnu nompi HDF5 && \
    rm -rf /tmp/ALF /tmp/tmp.*

USER user
